version: '2'
services:
  zookeeper:
    build: 3party/zookeeper
    expose:
      - 2181
  kafka:
    build: 3party/kafka
    expose:
      - 9092
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_PORT: 9092
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    links:
      - zookeeper
  chat:
    build: chat
    environment:
      KAFKA: kafka:9092
    ports:
      - 8080:8080
    links:
      - kafka
